### ISSUE TITLE
Mulighet for å filtrere ut en workflow fra et repo

### ISSUE THREAD

**Issue by taniaholst** [navikt/ghep#126]
Juhuuu! Ønsker å få beskjed i Slack-kanalen "#team-navno-failover-prod" KUN dersom [Deploy til prod-failover](https://github.com/navikt/nav-enonicxp-frontend/actions/workflows/deploy-failover.prod.yml)-workflowen feiler i `nav-enonicxp-frontend` repoet.

Noe i denne duren:

```
    team-nav-no:
        workflows: "#team-navno-failover-prod"
            config:
                repo: "nav-enonicxp-frontend"
                    action: "Deploy til prod-failover"
```
