### ISSUE TITLE
Mulighet for å kun få commits til default branch

### ISSUE THREAD

**Issue by heyvard** [navikt/ghep#4]
Commits fra alle brancher kan være litt støyete. Det hadde vært nice å kunne velge å bare få commits til default branch. 
Forslag til konfigurasjon:

```
nada:
 commits: #nada-commits
 issues: #nada-issues
 pulls: #nada-pull-requests
 only-default-branch-commits: true
```
